apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: demo
  labels:
    app: demo
spec:
  strategy:
    canary:
      steps:
      - setWeight: 40   # 40% of traffic to canary (new version)
      - pause: {}       # Pause to monitor
      - setWeight: 40   # Keep traffic at 40% (or adjust as needed)
      - pause: {}       # Pause again for monitoring
      canaryService: demo-canary  # Canary service for the new version (green)
      stableService: demo         # Stable service for the old version (blue)
      trafficRouting:
        istio:
           virtualService: 
            name: istio-vs
            routes:
            - primary  # Using Istio's virtual service for traffic management
  replicas: 5
  revisionHistoryLimit: 4
  selector:
    matchLabels:
      app: demo
      version: green     # Update this to match the new version "green"
  template:
    metadata:
      labels:
        app: demo
        version: green    # Label the new version as "green"
    spec:
      containers:
      - name: demo
        image: argoproj/rollouts-demo:green   # Use the new image (green version)
        imagePullPolicy: Always
        ports:
        - name: web
          containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "140m"
